# This connects the Workload Identity GCP service account with the Kubernetes
# service account used by '{{cookiecutter.deployment_name}}'
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{cookiecutter.deployment_name}}-wi-iampolicy
  namespace: dapla
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    # Matches SA created in '{{cookiecutter.deployment_name}}-wi-iamserviceaccount.yaml'
    name: {{cookiecutter.deployment_name}}-wi-sa
    namespace: dapla
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:prod-bip.svc.id.goog[dapla/{{cookiecutter.deployment_name}}-sa]
