# This is the Workload Identity service account created for '{{cookiecutter.deployment_name}}'.
# IAM is handled separately
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{cookiecutter.deployment_name}}-wi-sa #Max 30 characters
  namespace: dapla
spec:
  displayName: "Workload identity service account for dapla {{cookiecutter.deployment_name}} in prod-bip cluster"
